# -*- coding: utf-8 -*-
import hashlib
import uuid


def clear_single_lists(data: dict) -> dict:
    """Remove unneeded lists from the dictionary object generated by the schema.
    """
    for k, v in data.items():
        if isinstance(v, list):
            if len(v) == 1:
                data[k] = v[0]
            else:
                # Try apply the function to all items on the list.
                data[k] = [clear_single_lists(x) for x in v]

        # Recurse if we find the single item is a dictionary.
        if isinstance(data[k], dict):
            data[k] = clear_single_lists(data[k])
    return data


def seeded_uuid(name: str) -> str:
    """ Create a unique UUID based on the given input string.

    Adapted from: https://stackoverflow.com/a/55807344/14506150
    """
    m = hashlib.md5()
    m.update(name.encode('utf-8'))
    new_uuid = uuid.UUID(m.hexdigest(), version=4)
    return str(new_uuid)
